import { router, useLocalSearchParams } from 'expo-router'
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { useCatalog } from '@/lib/catalog'
import { useCart } from '@/lib/cart'
import { useTheme } from '@/lib/theme'
import { useToast } from '@/lib/toast'
import { money } from '@/lib/types'

export default function ProductDetailScreen() {
  const { theme } = useTheme()
  const { products } = useCatalog()
  const { add } = useCart()
  const { show } = useToast()
  const { id } = useLocalSearchParams<{ id: string }>()
  const product = products.find(item => item.id === id)
  if (!product) return <View style={[styles.center, { backgroundColor: theme.background }]}><ActivityIndicator color={theme.blue} /></View>
  return <ScrollView style={{ backgroundColor: theme.background }} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.top}><Pressable onPress={() => router.back()} style={[styles.back, { backgroundColor: theme.surface, borderColor: theme.line }]}><Ionicons name="arrow-back" size={19} color={theme.ink} /></Pressable><Text style={[styles.topTitle, { color: theme.muted }]}>Product details</Text><Pressable onPress={() => router.push('/(tabs)/cart')}><Ionicons name="cart-outline" size={23} color={theme.ink} /></Pressable></View><View style={[styles.imageWrap, { backgroundColor: theme.softBlue }]}><Image source={{ uri: product.image }} style={styles.image} /><View style={[styles.badge, { backgroundColor: theme.yellow }]}><Text style={{ color: theme.ink, fontSize: 11, fontWeight: '900' }}>DEAL</Text></View></View><View style={styles.copy}><Text style={[styles.store, { color: theme.blue }]}>{product.store}</Text><Text style={[styles.name, { color: theme.ink }]}>{product.name}</Text><View style={styles.rating}><Ionicons name="star" size={16} color="#F59E0B" /><Text style={{ color: theme.ink, fontWeight: '800' }}>{product.rating}</Text><Text style={{ color: theme.muted }}>({product.reviews} reviews)</Text></View><Text style={[styles.price, { color: theme.ink }]}>{money(product.price)}</Text><Text style={[styles.oldPrice, { color: theme.muted }]}>Was {money(product.oldPrice)}</Text><View style={[styles.info, { backgroundColor: theme.surface, borderColor: theme.line }]}><Ionicons name="shield-checkmark-outline" size={20} color={theme.green} /><View style={{ flex: 1, gap: 4 }}><Text style={[styles.infoTitle, { color: theme.ink }]}>Shop with confidence</Text><Text style={{ color: theme.muted, fontSize: 12, lineHeight: 18 }}>Verified stock, secure checkout and delivery updates from CartUp.</Text></View></View>{product.description && <Text style={[styles.description, { color: theme.muted }]}>{product.description}</Text>}<Pressable style={[styles.button, { backgroundColor: theme.blue }]} onPress={async () => { await add(product); show('Item added to your cart'); router.push('/(tabs)/cart') }}><Ionicons name="cart-outline" size={20} color="#fff" /><Text style={styles.buttonText}>Add to cart</Text></Pressable></View></ScrollView>
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 50, gap: 18 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { width: 40, height: 40, borderRadius: 13, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, topTitle: { fontSize: 13, fontWeight: '800' }, imageWrap: { height: 330, borderRadius: 25, overflow: 'hidden', position: 'relative' }, image: { width: '100%', height: '100%', resizeMode: 'cover' }, badge: { position: 'absolute', left: 15, bottom: 15, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 }, copy: { gap: 8 }, store: { fontSize: 12, fontWeight: '900' }, name: { fontSize: 26, lineHeight: 32, fontWeight: '900', letterSpacing: -.6 }, rating: { flexDirection: 'row', alignItems: 'center', gap: 5 }, price: { fontSize: 25, fontWeight: '900', marginTop: 5 }, oldPrice: { fontSize: 12, textDecorationLine: 'line-through' }, info: { flexDirection: 'row', alignItems: 'center', gap: 10, borderRadius: 15, borderWidth: 1, padding: 13, marginTop: 8 }, infoTitle: { fontSize: 13, fontWeight: '900' }, description: { fontSize: 13, lineHeight: 21, marginTop: 5 }, button: { minHeight: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 9, marginTop: 7 }, buttonText: { color: '#fff', fontSize: 14, fontWeight: '900' } })
